FROM golang:1.20 as build

WORKDIR /app

COPY ./src/go.mod /app
COPY ./src/go.sum /app
COPY ./src /app
RUN go mod download
RUN go build -o main main.go

FROM golang:1.20
COPY --from=build /app/main ./
EXPOSE 80
CMD ./main
